### ISSUE TITLE
Nightly compiler required for: "use { super::{ super::symbol, }, };

### ISSUE THREAD

**Issue by nospam3089** [rust-analyzer/rust-analyzer#11249]
This [urlo thread](https://users.rust-lang.org/t/extern-location-for-sorted-collections-does-not-exist/68312/4) urged me to post here. As stated in the thread, I gave *rust-analyzer* a try and found it to be unstable. Just as one should be expecting from that it is only available through +nightly. Version used: `rust-analyzer 8e9ccbf 2022-01-09 dev`.

If attempting to navigate the following code with `ALEGoToDefinition` in *vim-ale*, one only seems to be able to get as deep as into `other_func()`. Any attempt to find `unknown_func()` fails.

src/main.rs
```rust
use my_crate::some_func;
fn main() { some_func(); }
```

src/lib.rs
```rust
mod some_module {
    pub fn unknown_func() {
        println!("This function runs successfully, but is invisible to rust-analyzer!");
    }
}

mod other_module {
    pub mod some_submodule {
        use { super::{ super::unknown_func, }, };

        pub fn other_func() { unknown_func() }
    }

    pub use some_submodule::*;
}

use { some_module::unknown_func, other_module::other_func, };
pub fn some_func() { other_func(); }
```

Running `ALEInfo` shows the following error message: (no attempts to study nor to understand the logs in full have been done)

```
error: the option 'Z' is only accepted on the nightly compiler
```

Removing braces makes *rust-analyzer* able to resolve the symbol, but that is easier to do in this reduced example than the real codebase I encountered the problem in.

**Comment by bjorn3** [comment]
> Running `ALEInfo` shows the following error message: (no attempts to study nor to understand the logs in full have been done)
> 
> ```
> error: the option 'Z' is only accepted on the nightly compiler
> ```

Does it show anything before that line? Do you have any configuration that passes an unstable flag to rustc? AFAIK rust-analyzer doesn't pass any `-Z` flags to rustc ever unless you tell it to. The configuration could come from for example a `.cargo/config.toml` file. Also does `cargo check --workspace --all-targets` work?

> Removing braces makes rust-analyzer able to resolve the symbol, but that is easier to do in this reduced example than the real codebase I encountered the problem in.

I am honestly surprised that that code is valid rust. Guess I learnt something new about rust. It should still be fixed in rust-analyzer though.

**Comment by nospam3089** [comment]
Ooops, sorry! It seems I was a bit quick jumping to conclusions. That actual error message was unrelated, and caused by me failing to disable other linters. Once running in a more clean environment, the only thing showing up in the log is *rust-analyzer* launching. Finding `unknown_func()` still fails.

```
% cargo clean; cargo check --workspace --all-targets; echo $?
    Checking my_crate v0.0.1 (/my_crate)
    Finished dev [unoptimized + debuginfo] target(s) in 1.20s
0
```

I take it you are able to reproduce?

**Comment by Veykril** [comment]
Can reproduce that we fail to resolve if the use tree looks like given in your snippet
```rs
use super::super::unknown_func; // makes resolution work in the snippet
use { super::{ super::unknown_func, }, }; // fails resolution in the snippet
```
