### ISSUE TITLE
'Check' doesn't complete (or is very slow) for Nushell

### ISSUE THREAD

**Issue by jonathandturner** [rust-analyzer/rust-analyzer#2909]
We've been using (and loving!) rust analyzer for months to write Nushell. It's been great.

Recently, though, we've hit a few issues that make it difficult to use:

* the cargo watch set to 'check' sometimes doesn't finish and the indicator keeps spinning (or takes a very long time to finish)
* no indicator is shown, and instead 1000+ syntax errors are shown.  After 20-30 seconds the correct errors are shown

In general, things feel much slower than they used to be, and much less reliable.  I'm happy to help explore what it might be, as I'm eager to get back to using ra.

This is on a recent master of Nushell

**Comment by bjorn3** [comment]
How much time does `cargo check` take?

**Comment by jonathandturner** [comment]
@bjorn3 - about 4 seconds for an incremental change

**Comment by bjorn3** [comment]
Are you using Windows? A performance issue on Windows has been (mostly) fixed just today (#2906).

**Comment by jonathandturner** [comment]
I'm on Linux. An Ubuntu-based distro called Pop! OS

**Comment by bjorn3** [comment]
Nushell seems to use a lot of off by default features. rust-analyzer uses `--all-features` by default. Is `cargo check --all-features` a lot slower?

**Comment by bjorn3** [comment]
It also passes `--all-targets`.

**Comment by bjorn3** [comment]
I can reproduce at least some of the slowness. I think ~15s.

**Comment by bjorn3** [comment]
It seems that most time is spent by rustc actually performing a check build.

**Comment by jonathandturner** [comment]
We use a similar, but slightly different setup.

Here are my timings:

(no change)
```
$ cargo check --all --features=stable
    Finished dev [unoptimized + debuginfo] target(s) in 0.25s
```

After a change:
```
$ cargo check --all --features=stable
    Checking nu v0.8.1 (/home/jonathan/Source/nushell)
    Finished dev [unoptimized + debuginfo] target(s) in 5.08s
```

In rust-analyzer, I'm seeing:

* No changes: ~5 secs
* Simple change: 5-10 secs

I also tested the startup times:
* cargo test --all - 2 mins 58 secs
* On startup (rust-analyzer, same configuration) - 5 mins 50 secs to finish

Something else I noticed is that it would sometimes get "stuck" on certain crates, even if those crates would build fairly quickly on the commandline.  One example:

![Screenshot from 2020-01-27 13-23-55](https://user-images.githubusercontent.com/547158/73144516-58e3ef00-410b-11ea-97c4-652b57999e04.png)

It animated this for at least 30 secs, even though on the commandline that crate would have finished more quickly.

**Comment by matklad** [comment]
cc @kiljacken

**Comment by kiljacken** [comment]
I've added some timing and debug output over on the `check-slowdown` branch of [kiljacken/rust-analyzer](https://github.com/kiljacken/rust-analyzer/).

It would be great if you could build from the branch and run VSCode with the following command, and share the output from the "Rust Analyzer Language Server" dropdown selection on the "Output" tab of the bottom panel:
`env RUST_LOG=ra_cargo_watch=trace RA_PROFILE="*" code .`

**Comment by matklad** [comment]
I am semi-successful at reproducing this. Yesterday I've got a reliable repro at my home machine (when hacking on an unrelated thing), but at my work machine (which is almost a complete clone of the home one, lol) everything works.

Regardless, we've pushed a couple of optimizations recently, they should speed the things up, and at least one of them has a potential of making things significantly faster (we forget to buffer cargo's output).

**Comment by matklad** [comment]
Ok, I think we've finally squashed this one!

The problem was that, when reacting to `cargo check` output, we were scheduling diagnostics computation onto the main loop, and not onto the threadpool.

I've made a release with this change: https://github.com/rust-analyzer/rust-analyzer/releases/tag/2020-01-29

**Comment by Jos635** [comment]
I'm not the one that made this issue, but I think I experienced the same problem. Unfortunately I'm still having the issue where `cargo check` never completes (VS Code, Kubuntu 19.04, commit 7a2b87db compiled from source).

 Output of the command that's being run, i.e.:

    cargo check --message-format=json --manifest-path {...}/Cargo.toml --all-targets

is 

    Finished dev [unoptimized + debuginfo] target(s) in 0.21s

Strangely enough I don't have this issue 100% of the time (for this one project), I've been able to launch VS Code once where it worked properly for a while before the issues started again. If the issue occurs, both the `ra_lsp_server` process and the `code` process use a full CPU core at 100% while the `cargo` process seems to be sleeping.

Would logs from the `check-slowdown` still help?

**Comment by kiljacken** [comment]
That should probably be a warning and not an error, but shouldn't really cause the check to hang. The most useful thing would be a backtrace of all threads from a debugger, at that shows where we're spinning.

**Comment by matklad** [comment]
Hm, it should be an error, if we pass `--message-format=json`, we only should get jsons on stdout.

**Comment by Jos635** [comment]
Alright, I think I've figured it out!

I was using a proc macro that `println!`ed some debugging info. That debugging info appears in the output used by rust-analyzer, but not in the output when you run `cargo check` from the command line for some reason.

After removing the `println!`s everything is now working as it should.

Not sure how the parsing of `cargo check` works, but maybe it's spinning on reading the same invalid JSON character again and again?

**Comment by kiljacken** [comment]
That seems plausible, I'll take a closer look and report it upstream if that is the case.

**Comment by jonathandturner** [comment]
This seems to fix with the latest ra
