### ISSUE TITLE
Can't disable the "workspace loaded" notification

### ISSUE THREAD

**Issue by RReverser** [rust-analyzer/rust-analyzer#3176]
I've had "workspace loaded" notification disabled in settings for a while now, and keep trying to update rust-analyzer hoping that this was a temporary bug, but doesn't seem so as notification keeps appearing on every single load:

![image](https://user-images.githubusercontent.com/557590/74610802-4d725b00-50ee-11ea-9e7f-97dd20f3eaf1.png)
![image](https://user-images.githubusercontent.com/557590/74610805-55ca9600-50ee-11ea-87d1-e429074822dc.png)

**Comment by lnicola** [comment]
There's no setting for it (we should remove it if there is). You need to configure it [like this](https://github.com/rust-analyzer/rust-analyzer/issues/2719#issuecomment-586512737).

**Comment by RReverser** [comment]
Well the settings clearly exists in the UI and has existed for a while now (it's been at least half a year since I enabled it), so it seems better to fix it rather than remove altogether.

**Comment by lnicola** [comment]
See https://github.com/rust-analyzer/rust-analyzer/issues/2189.

The idea is to separate client and server options. The server ones are currently configured via that JSON blob, but it's not ideal.

**Comment by Veetaha** [comment]
Why do we store feature flags as an hash-map and not a strictly-typed object instead? Might I ask you to elaborate on this @matklad?

**Comment by lnicola** [comment]
See https://github.com/rust-analyzer/rust-analyzer/issues/2189#issuecomment-551342973. Because that's how it's implemented right now, it seems to me.

**Comment by matklad** [comment]
>Might I ask you to elaborate on this @matklad?

https://github.com/rust-analyzer/rust-analyzer/blob/953dbe3e02fa87bab2f12452746e6c50a47ac153/crates/ra_ide_db/src/feature_flags.rs#L12-L13

I still believe that that's the right decision for the internal data structure. But ideally we should not expose this in UI, and we should fix the present regression

**Comment by matklad** [comment]
Wait, this is not a regression (at least, not the recent one). We've removed this setting about half a year ago: https://github.com/rust-analyzer/rust-analyzer/commit/69bbe79c5037eb3cd00744593d1836e45a6f56e1#diff-9234de0bfa99228a67ea76a4391c86f1L168

So, we still should figure out our overall approach to settings (it is still to be designed TT), but this is unrelated to recent VS Code config refactoring, and doesn't require immediate action.

**Comment by lnicola** [comment]
It probably shows up in the UI when it's already set, even if it no longer exists anymore. The JSON settings editor displays it in gray, but the graphical one probably does nothing.

**Comment by RReverser** [comment]
> The JSON settings editor displays it in gray, but the graphical one probably does nothing.

It doesn't show it in grey even in JSON for me:
![image](https://user-images.githubusercontent.com/557590/74655435-41d17380-5184-11ea-8f45-8e7cf646e7df.png)

And toggling the option doesn't make it disappear in the UI.

For what it's worth, the extension version is `0.2.20200211-dev` which seems fresh enough.

**Comment by RReverser** [comment]
> There's no setting for it (we should remove it if there is). You need to configure it [like this](https://github.com/rust-analyzer/rust-analyzer/issues/2719#issuecomment-586512737).

Btw, I've tried this as well, and still getting the notification on each load :(

![image](https://user-images.githubusercontent.com/557590/74655691-ac82af00-5184-11ea-8e6d-74e8b9b6e8ae.png)

**Comment by matklad** [comment]
Hm, could it be the case that you have two version of the extension installed? We renamed it from `ra-lsp` to `rust-analyzer` about a month ago, and the update should have cleaned up the old one, but perhaps it didn't?

**Comment by lnicola** [comment]
For me it looks like this:

![image](https://user-images.githubusercontent.com/308347/74657552-23c23e00-5199-11ea-9bba-d9901bfbd49a.png)

**Comment by Veetaha** [comment]
@RReverser, might I ask you, please, to open the command palette with <kbd>Ctrl+Shift+P</kbd>, write `Toggle Developer Tools` and press enter to open the Developer Tools, then open `Console` tab and send its contents here?
The effective config that we should be printed there under `Using configuration:`
If there is nothing like that there, you are most likely using an old version of our extension...

**Comment by RReverser** [comment]
> We renamed it from ra-lsp to rust-analyzer about a month ago, and the update should have cleaned up the old one, but perhaps it didn't?

I mean, the settings are in the `rust-analyzer` namespace and the installed extension is called that way too...

![image](https://user-images.githubusercontent.com/557590/74670610-6e47b880-51a1-11ea-9dc2-fd772144e609.png)

> might I ask you, please, to open the command palette with Ctrl+Shift+P, write Toggle Developer Tools and press enter, then open Console tab and send its contents here?
The effective config that we use should be printed there under Using configuration:
If there is nothing like that there, you are most likely using an old version of our extension...

It shows up correctly I think:

![image](https://user-images.githubusercontent.com/557590/74670671-90413b00-51a1-11ea-8467-ad9f20ac5a99.png)

**Comment by RReverser** [comment]
Okay, yeah, I actually hunted down a copy of `ra-lsp` that was loading from `.../.vscode/extensions/...`, but for some reason didn't show up on the list of installed extensions and still ran (and showed some conflict errors in DevTools console of VSCode).

Removing it seems to have gotten settings UI & JSON into a saner state.

**Comment by Veetaha** [comment]
I am not totally sure, it can be that we currently don't ship for your platform, but anyway I'd recommend installing rust-analyzer from VSCode

**Comment by eminence** [comment]
I think this issue can be closed now (see #4253)
