### ISSUE TITLE
Rust-analyser not processing results from next() method of async_std::stream::StreamExt

### ISSUE THREAD

**Issue by SillyMoo** [rust-analyzer/rust-analyzer#4243]
Rust analyser is not able to process the next() method at the end of the attached rust file. This works ok with vs-code and rls, but vs-code with rust-analyzer it fails to return a type for the result of next().

[src.zip](https://github.com/rust-analyzer/rust-analyzer/files/4564747/src.zip)

**Comment by bjorn3** [comment]
Maybe a duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/1791? (`async`/`await` support)

<details><summary>Content of the zip, for mobile users</summary>

```rust
use async_amqp::*;
use async_std::stream::StreamExt;
use lapin::{
    message::DeliveryResult, options::*, publisher_confirm::Confirmation, types::FieldTable,
    BasicProperties, Connection, ConnectionProperties, Result,
};
use log::info;
use futures::channel::mpsc;
use futures::sink::SinkExt;

struct TaskProperty {
    name: String,
    sval: Option<String>,
    nval: Option<i32>,
}
struct Task {
    task_id: String,
    task_ulid: String,
    sample_id: String,
    vm_profile: String,
    task_properties: Vec<TaskProperty>,
}

#[async_std::main]
async fn main() -> Result<()> {

    env_logger::init();
    
    let (tx, mut rx)= mpsc::channel::<String>(100);


    let addr = "amqp://localhost:5673";
    let conn = Connection::connect(&addr, ConnectionProperties::default().with_async_std()).await?;
    let queue_name = "bob";
    info!("CONNECTED");

    let channel_a = conn.create_channel().await?;
    let channel_b = conn.create_channel().await?;

    let queue = channel_a
        .queue_declare(
            queue_name,
            QueueDeclareOptions::default(),
            FieldTable::default(),
        )
        .await?;

    info!("Declared queue {:?}", queue);

    let consumer = channel_b
        .clone()
        .basic_consume(
            queue_name,
            "my_consumer",
            BasicConsumeOptions::default(),
            FieldTable::default(),
        )
        .await?;

    consumer.set_delegate(move |delivery: DeliveryResult| {
        let channel_b = channel_b.clone();
        let mut tx = tx.clone();
        async move {
            let delivery = delivery.expect("error caught in in consumer");
            if let Some(delivery) = delivery {
                channel_b
                    .basic_ack(delivery.delivery_tag, BasicAckOptions::default())
                    .await
                    .expect("failed to ack");
                tx.send(String::from_utf8(delivery.data).unwrap()).await.unwrap();
            }
        }
    });

    let payload = b"Hello world!";

    
    let confirm = channel_a
        .basic_publish(
            "",
            queue_name,
            BasicPublishOptions::default(),
            payload.to_vec(),
            BasicProperties::default(),
        )
        .await?
        .await?;
    assert_eq!(confirm, Confirmation::NotRequested);
    let res = rx.next().await.unwrap();
    info!("Got {:?}", res);
    Ok(())
}
```

```toml
[package]
name = "ivm2_rust"
version = "0.1.0"
authors = ["Chris Mills <Chris_Mills@symantec.com>"]
edition = "2018"

[dependencies]
smol = "0.1.4"
log = "0.4.8"
async-amqp = "0.1.0-beta3"
env_logger = "0.7.1"
futures = "0.3.4"

[dependencies.async-std]
version = "^1.0"
features = ["default"]

[dev-dependencies.async-std]
version = "^1.0"
features = ["attributes", "default"]

[dependencies.lapin]
version = "1.0.0-beta3"
default-features = true
```

</details>

**Comment by SillyMoo** [comment]
It's worth noting that the failure is at the call to next() rather than the call to await. So not quite sure if it is the same thing.

**Comment by flodiebold** [comment]
It looks to me like we're not managing to expand the [`extension_trait!` macro](https://github.com/async-rs/async-std/blob/370642ef3e41681b063f69796e427ebb2d51db68/src/stream/stream/mod.rs#L146).

**Comment by edwin0cheng** [comment]
Yeah, it is related to #4039

**Comment by edwin0cheng** [comment]
@SillyMoo #4283 is landed, and it should fix this issue.

**Comment by SillyMoo** [comment]
Great stuff, thanks.

**Comment by lnicola** [comment]
Update: we don't resolve `next`.

**Comment by lnicola** [comment]
Triage: this still happens. It looks like we still don't expand that macro correctly:

![Uploading image.png…]()

**Comment by lnicola** [comment]
A first step here might be to extract `extension_trait!` macro and see if we can come up with a smaller reproducible example.

**Comment by lnicola** [comment]
Somewhat minimized test case:

```rust
macro_rules! extension_trait {
    (

        pub trait $name:ident {
            $($body_base:tt)*
        }
    ) => {

        #[cfg(feature = "docs")]
        pub trait $name {
            extension_trait!(@doc () $($body_base)*);
        }
    };

    (@doc ($($head:tt)*) $token:tt $($tail:tt)*) => {
        extension_trait!(@doc ($($head)* $token) $($tail)*);
    };

    (@doc ($($head:tt)*)) => { $($head)* };
}

extension_trait! {
    pub trait Stream {
        type Item;
    }
}
```

```
// Recursive expansion of extension_trait! macro
// ==============================================

#[cfg(feature = "docs")]pub trait Stream {
  extension_trait!(@doc()type Item;
  );
  
}
```

**Comment by lnicola** [comment]
CC @edwin0cheng :-)

**Comment by lnicola** [comment]
Triage: https://github.com/rust-analyzer/rust-analyzer/issues/4243#issuecomment-768459223 still happens after the recent macro fixes.

**Comment by edwin0cheng** [comment]
@lnicola  In fact, https://github.com/rust-analyzer/rust-analyzer/issues/4243#issuecomment-768459223 is CORRECT expansion. 

Note that rustc  will ignore macro expansion inside `#[cfg(feature = "docs")]`  if that feature is off.

**Comment by edwin0cheng** [comment]
It is because we ignore macro expansion under `#[cfg(feature = "docs")]` if that feature is off.

**Comment by edwin0cheng** [comment]
This rabbit hole is quite deep :)

The actual problem of [`extension_trait!`](https://github.com/async-rs/async-std/blob/370642ef3e41681b063f69796e427ebb2d51db68/src/stream/stream/mod.rs#L146) macro are the following lines:

```
        // When not rendering docs, re-export the base trait from the futures crate.
        #[cfg(not(feature = "docs"))]
        pub use $base as $name;

        // The extension trait that adds methods to any type implementing the base trait.
        #[doc = $doc_ext]
        pub trait $ext: $name {
            extension_trait!(@ext () $($body_ext)*);
        }
```

And noted that by default, `#[cfg(not(feature="docs"))] will be false in our RA default cfg handling code, but `#[cfg(feature = "docs"]` will also failed to expand as I mentioned before. 

There are no code to implement the `next()` method, so it cannot be inference.

**Comment by lnicola** [comment]
> And noted that by default, #[cfg(not(feature="docs"))] will be false in our RA default cfg handling code

Wait, why? Is that how it's supposed to work?

**Comment by jonas-schievink** [comment]
The expansion in https://github.com/rust-analyzer/rust-analyzer/issues/4243#issuecomment-768459223 looks correct to me. After all, the `#[cfg]` *is* disabled there, and I think this matches rustc behavior (not that it matters, since the entire trait is `cfg`d out).

**Comment by jonas-schievink** [comment]
Removing the `#[cfg]` or adding `not(...)` makes it expand like I'd expect, producing `pub trait Stream { type Item; }`.

**Comment by PorkSausages** [comment]
I don't really understand what's being said in this thread, how do I configure rust-analyzer to work properly in this instance if it has been fixed?

**Comment by lnicola** [comment]
@PorkSausages it hasn't been fixed and I'm still not sure what's wrong.

**Comment by jonas-schievink** [comment]
If I remove enough tokens from the `StreamExt` trait, it eventually expands successfully. Some logging confirms that we are running into the recursion limit here:

https://github.com/rust-analyzer/rust-analyzer/blob/9ba6cfa9c70c153b71982b07f39aab73a5252ef8/crates/hir_def/src/data.rs#L380-L382

This happens because `extension_trait!` is internally using a token muncher to consume the input, and the input is very large.

**Comment by jonas-schievink** [comment]
`async-std` sets `#![recursion_limit = "2048"]`, so I'd say it's expected that this doesn't work in rust-analyzer.

**Comment by lnicola** [comment]
Fixed in #11360.

Unfortunately, our macro expansion code is somewhat slow, so performance might not be ideal when working on such code: #11363.
