### ISSUE TITLE
if rustfmt is not installed, formatting silently fails

### ISSUE THREAD

**Issue by skrap** [rust-analyzer/rust-analyzer#4249]
If `rustfmt` isn't installed, then there is no error upon executing the `Format Document` command.  However, nothing happens.  Installing `rustfmt` via `rustup component add rustfmt` fixes the issue.

It would have been helpful to have an error dialog of some kind explaining what went wrong and how to fix it, or even something which offers to install `rustfmt` for the user!

Hopefully an easy fix!

Also, could possibly also be the root cause of #1955, maybe others?

**Comment by matklad** [comment]
Should be fixed here: https://github.com/rust-analyzer/rust-analyzer/blob/4d33cdcfb2e06088c8bccc57565224f8a377d899/crates/rust-analyzer/src/main_loop/handlers.rs#L651

**Comment by andreevlex** [comment]
I trying remove rustfmt.

```sh
rustup component remove rustfmt
```

When `rustfmt` missing status code set `1`

```sh
user $ rustfmt
```

output

```log
error: 'rustfmt' is not installed for the toolchain 'stable-x86_64-unknown-linux-gnu'
To install, run `rustup component add rustfmt --toolchain stable-x86_64-unknown-linux-gnu`

```

exit code 

```sh
user $ echo $?
1
```

executable exists after remove 

```sh
user $ which rustfmt
/home/user/.cargo/bin/rustfmt
```

**Comment by DeltaManiac** [comment]
I tried to reproduce this issue on Windows with the following rust version and rust-analyzer version
```
C:\Users\DeltaManiac>rust-analyzer  --version
rust-analyzer d1c1c01
```
```
C:\Users\DeltaManiac>rustup show
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\DeltaManiac\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-msvc
nightly-2019-04-21-x86_64-pc-windows-msvc
nightly-x86_64-pc-windows-msvc (default)

active toolchain
----------------

nightly-x86_64-pc-windows-msvc (default)
rustc 1.45.0-nightly (2454a68cf 2020-05-04)
```

However the observation is that an error message does pop up when trying to save or format the document with a missing rustfmt.exe .

![Issue-4249](https://user-images.githubusercontent.com/3689561/81102919-eebebf80-8f2d-11ea-9e87-d509780bc38f.gif)
I 

Is this behavior that should occur or do we need to change it ?

**Comment by skrap** [comment]
I should have said in the original report: I'm using the stable-x86_64-unknown-linux-gnu toolchain via rustup, on pop os 19.10 (based on ubuntu 19.10).

**Comment by miDeb** [comment]
So I decided to take a look on this:
You can reproduce this by running `rustup component remove rustfmt`. Then, formatting in VS Code does nothing. Running `rustfmt` manually prints to stderr:
```
error: 'rustfmt' is not installed for the toolchain 'nightly-x86_64-unknown-linux-gnu'
To install, run `rustup component add rustfmt
```
and exits with code 1.
Note that `rustup component list` also still shows rustfmt, so that can not be used to check if it is available. I guess we could just check if this message was printed to stderr and show a notification. But what if someone intentionally removed rustfmt? I guess always showing a notification would be annoying...
While trying to implement that, i noticed this [error code ](https://github.com/rust-analyzer/rust-analyzer/blob/4d33cdcfb2e06088c8bccc57565224f8a377d899/crates/rust-analyzer/src/main_loop/handlers.rs#L677) which is the same as this [constant](https://github.com/rust-analyzer/rust-analyzer/blob/4d33cdcfb2e06088c8bccc57565224f8a377d899/crates/rust-analyzer/src/main_loop.rs#L58). Is this intentional? It seems there is a special case where it [gets ignored](https://github.com/rust-analyzer/rust-analyzer/blob/4d33cdcfb2e06088c8bccc57565224f8a377d899/crates/rust-analyzer/src/main_loop.rs#L926).
Unrelated: I somehow couldn't find where [this log](https://github.com/rust-analyzer/rust-analyzer/blob/4d33cdcfb2e06088c8bccc57565224f8a377d899/crates/rust-analyzer/src/main_loop/handlers.rs#L671) is printed...
I'm new to this project and Rust in general so sorry if I missed something.

**Comment by bjorn3** [comment]
> Note that rustup component list also still shows rustfmt, so that can not be used to check if it is available.

Does it say `rustfmt-x86_64-unknown-linux-gnu (installed)` or `rustfmt-x86_64-unknown-linux-gnu`? In the later case it isn't installed. You can install it using `rustup component add rustfmt`.

**Comment by miDeb** [comment]
> In the later case it isn't installed

I did not know that! Do you think it would be better to check this once when starting rust-analyzer? And maybe add a setting to turn this check off.

**Comment by RantingBob** [comment]
I have a similar error.  In my case, with the latest nightly as of making this post, rustfmt doesn't run, or silently fails (I'm not sure which), even though I have rustfmt installed and can invoke it manually.

**Comment by 0xd4d** [comment]
One reason it could 'fail' to run rustfmt even if it's installed is if rust-analyzer is using 100% of one core doing something. VS code seems to stop it after about 40-50 seconds (see the logs).
