### ISSUE TITLE
Cannot activate rust-analyzer: bootstrap error

### ISSUE THREAD

**Issue by mburszley** [rust-analyzer/rust-analyzer#5274]
I started seeing this today and haven't seen it before.  It might be related to #5009? but I'm not certain.

Windows 10 20H2
vscode v1.46.1

Rustup v1.22.1
Cargo/Rustc v1.44.1

Toolchains:
* stable-x86_64-pc-windows-msvc (default)
* nightly-x86_64-pc-windows-msvc

Components:
* cargo-x86_64-pc-windows-msvc
* clippy-x86_64-pc-windows-msvc
* rls-x86_64-pc-windows-msvc
* rust-analysis-x86_64-pc-windows-msvc
* rust-docs-x86_64-pc-windows-msvc
* rust-src
* rust-std-x86_64-pc-windows-msvc
* rustc-x86_64-pc-windows-msvc
* rustfmt-x86_64-pc-windows-msvc

Options:

```json
{
  "rust-analyzer.trace.extension": true,
  "rust-analyzer.cargo.loadOutDirsFromCheck": true,
  "rust-analyzer.updates.askBeforeDownload": false,
  "rust-analyzer.updates.channel": "nightly"
}
```

Error:

```
INFO [7/8/2020, 7:28:33 PM]: Extension version: 0.3.234-nightly
INFO [7/8/2020, 7:28:33 PM]: Using configuration {
  diagnostics: { enable: true, warningsAsInfo: [], warningsAsHint: [] },
  lruCapacity: null,
  files: { watcher: 'client', exclude: [] },
  notifications: { cargoTomlNotFound: true },
  cargo: {
    noDefaultFeatures: false,
    allFeatures: false,
    features: [],
    loadOutDirsFromCheck: true,
    target: null
  },
  rustfmt: { extraArgs: [], overrideCommand: null },
  checkOnSave: {
    enable: true,
    extraArgs: [],
    command: 'check',
    overrideCommand: null,
    allTargets: true,
    allFeatures: null,
    features: null
  },
  cargoRunner: null,
  runnableEnv: null,
  inlayHints: {
    enable: true,
    typeHints: true,
    chainingHints: true,
    parameterHints: true,
    maxLength: 20
  },
  completion: {
    addCallParenthesis: true,
    addCallArgumentSnippets: true,
    postfix: { enable: true }
  },
  callInfo: { full: true },
  updates: { channel: 'nightly', askBeforeDownload: false },
  serverPath: null,
  trace: { server: 'off', extension: true },
  procMacro: { enable: false },
  debug: {
    engine: 'auto',
    sourceFileMap: {
      '/rustc/<id>': '${env:USERPROFILE}/.rustup/toolchains/<toolchain-id>/lib/rustlib/src/rust'
    },
    openDebugPane: false,
    engineSettings: {}
  },
  lens: { enable: true, run: true, debug: true, implementations: true },
  hoverActions: {
    enable: true,
    implementations: true,
    run: true,
    debug: true,
    gotoTypeDef: true
  },
  linkedProjects: null,
  withSysroot: true
}
INFO [7/8/2020, 7:28:33 PM]: PersistentState: {
  lastCheck: 1594250307755,
  releaseId: 28336980,
  serverVersion: '0.3.208-nightly'
}
DEBUG [7/8/2020, 7:28:33 PM]: Issuing request for released artifacts metadata to https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/tags/nightly
ERROR [7/8/2020, 7:28:33 PM]: Bootstrap error [TypeError: node_fetch_1.default is not a function
	at Object.fetchRelease (c:\Users\mburs\.vscode\extensions\matklad.rust-analyzer-0.3.234-nightly\out\src\main.js:15902:48)
	at getServer (c:\Users\mburs\.vscode\extensions\matklad.rust-analyzer-0.3.234-nightly\out\src\main.js:16235:31)
	at async bootstrapServer (c:\Users\mburs\.vscode\extensions\matklad.rust-analyzer-0.3.234-nightly\out\src\main.js:16145:18)
	at async bootstrap (c:\Users\mburs\.vscode\extensions\matklad.rust-analyzer-0.3.234-nightly\out\src\main.js:16095:18)
	at async tryActivate (c:\Users\mburs\.vscode\extensions\matklad.rust-analyzer-0.3.234-nightly\out\src\main.js:16022:24)
	at async activate (c:\Users\mburs\.vscode\extensions\matklad.rust-analyzer-0.3.234-nightly\out\src\main.js:15996:5)
	at async Promise.all (index 0)]
```

**Comment by imsiddiqi** [comment]
Getting the same error. I'm running the VS Code client on Windows 10 and server on Ubuntu 19.10, but also tested directly on Ubuntu. Was working fine yesterday...

Versions:

* rustc is 1.46.0-nightly (8ac1525e0 2020-07-07)
* rustup is 1.22.1
* VS Code is 1.46.1

Toolchains:

* stable-x86_64-unknown-linux-gnu
* nightly-x86_64-unknown-linux-gnu (default)

I tried re-installing rustup/toolchains but couldn't resolve the issue.

```
INFO [7/9/2020, 00:51:03]: Extension version: 0.3.234-nightly
INFO [7/9/2020, 00:51:03]: Using configuration {
  diagnostics: { enable: true, warningsAsInfo: [], warningsAsHint: [] },
  lruCapacity: null,
  files: { watcher: 'client', exclude: [] },
  notifications: { cargoTomlNotFound: true },
  cargo: {
    noDefaultFeatures: false,
    allFeatures: false,
    features: [],
    loadOutDirsFromCheck: false,
    target: null
  },
  rustfmt: { extraArgs: [], overrideCommand: null },
  checkOnSave: {
    enable: true,
    extraArgs: [],
    command: 'check',
    overrideCommand: null,
    allTargets: true,
    allFeatures: null,
    features: null
  },
  cargoRunner: null,
  runnableEnv: null,
  inlayHints: {
    enable: true,
    typeHints: true,
    chainingHints: true,
    parameterHints: true,
    maxLength: 20
  },
  completion: {
    addCallParenthesis: true,
    addCallArgumentSnippets: true,
    postfix: { enable: true }
  },
  callInfo: { full: true },
  updates: { channel: 'nightly', askBeforeDownload: true },
  serverPath: null,
  trace: { server: 'off', extension: true },
  procMacro: { enable: false },
  debug: {
    engine: 'auto',
    sourceFileMap: {
      '/rustc/<id>': '${env:USERPROFILE}/.rustup/toolchains/<toolchain-id>/lib/rustlib/src/rust'
    },
    openDebugPane: false,
    engineSettings: {}
  },
  lens: { enable: true, run: true, debug: true, implementations: true },
  hoverActions: {
    enable: true,
    implementations: true,
    run: true,
    debug: true,
    gotoTypeDef: true
  },
  linkedProjects: null,
  withSysroot: true
}
INFO [7/9/2020, 00:51:03]: PersistentState: {
  lastCheck: 1594224293665,
  releaseId: 28336980,
  serverVersion: '0.3.233-nightly'
}
DEBUG [7/9/2020, 00:51:03]: Issuing request for released artifacts metadata to https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/tags/nightly
ERROR [7/9/2020, 00:51:03]: [TypeError: node_fetch_1.default is not a function
	at Object.fetchRelease (/home/user/.vscode-server/extensions/matklad.rust-analyzer-0.3.234-nightly/out/src/main.js:15902:48)
	at bootstrapExtension (/home/user/.vscode-server/extensions/matklad.rust-analyzer-0.3.234-nightly/out/src/main.js:16118:31)
	at bootstrap (/home/user/.vscode-server/extensions/matklad.rust-analyzer-0.3.234-nightly/out/src/main.js:16094:11)
	at async tryActivate (/home/user/.vscode-server/extensions/matklad.rust-analyzer-0.3.234-nightly/out/src/main.js:16022:24)
	at async activate (/home/user/.vscode-server/extensions/matklad.rust-analyzer-0.3.234-nightly/out/src/main.js:15996:5)
	at async Promise.all (index 0)
	at async Promise.all (index 1)
	at async Promise.all (index 28)
	at async Promise.all (index 1)]
DEBUG [7/9/2020, 00:51:06]: Issuing request for released artifacts metadata to https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/tags/nightly
ERROR [7/9/2020, 00:51:06]: Bootstrap error [TypeError: node_fetch_1.default is not a function
	at Object.fetchRelease (/home/user/.vscode-server/extensions/matklad.rust-analyzer-0.3.234-nightly/out/src/main.js:15902:48)
	at getServer (/home/user/.vscode-server/extensions/matklad.rust-analyzer-0.3.234-nightly/out/src/main.js:16235:31)
	at processTicksAndRejections (internal/process/task_queues.js:89:5)
	at async bootstrapServer (/home/user/.vscode-server/extensions/matklad.rust-analyzer-0.3.234-nightly/out/src/main.js:16145:18)
	at async bootstrap (/home/user/.vscode-server/extensions/matklad.rust-analyzer-0.3.234-nightly/out/src/main.js:16095:18)
	at async tryActivate (/home/user/.vscode-server/extensions/matklad.rust-analyzer-0.3.234-nightly/out/src/main.js:16022:24)
	at async activate (/home/user/.vscode-server/extensions/matklad.rust-analyzer-0.3.234-nightly/out/src/main.js:15996:5)
	at async Promise.all (index 0)
	at async Promise.all (index 1)
	at async Promise.all (index 28)
	at async Promise.all (index 1)]
```

**Comment by Pytal** [comment]
I think this is related to #5262, @Veetaha any idea for a fix?

**Comment by Veetaha** [comment]
I recommend trying out today's new nightly version. It works for me

**Comment by mburszley** [comment]
@Veetaha My error is from two hours ago - has a new release come out in that time?

**Comment by Veetaha** [comment]
@mburszley 
Yup, exactly

**Comment by djc** [comment]
Is there some way I can force a new version update? I'm affected by this and the VS Code extensions marketplace tells me there's no newer version than the 0.3.234 that I've got already (I'm on the nightly channel).

**Comment by Veetaha** [comment]
You should uninstal it, install and switch to nightly again

**Comment by imsiddiqi** [comment]
Updating has resolved the issue for me as well.

**Comment by mburszley** [comment]
@Veetaha I'll follow-up this evening on whether it's resolved now.

**Comment by matklad** [comment]
Optimisticlally closing

**Comment by mburszley** [comment]
@matklad Thanks!  I had to uninstall/reinstall the extension for the update to actually take.

**Comment by justlevy20** [comment]
Closed, I know, but still having this issue in Oct 2022. The problem/solution I found was the file rust-analyzer-x86_64-unknown-linux-gnu did not have the executable flag set.

**Comment by GRAYgoose124** [comment]
> Closed, I know, but still having this issue in Oct 2022. The problem/solution I found was the file rust-analyzer-x86_64-unknown-linux-gnu did not have the executable flag set.

I want to report I have this same issue on the most recent nightly releases (10-23,10-15), I haven't tested any others but justlevy20's answer solved my problem as well with the marketplace version. (Didn't try it on the vsix) 

I'm using the linux_x86_64_unknown version with code on arch. One issue I'm having is despite my default toolchain being nightly, it keeps using a stable language server. (Even if i use override or rust-toolchain.toml), at least according to the config dumped and RA warnings for nightly only features.

**Comment by mrchip2k** [comment]
Same issue.
WSL Debian. Rust stable, rustc 1.64. Only one toolchain.
It works when launching Vscode in Windows.
I can't figure out where `rust-analyzer-x86_64-unknown-linux-gnu` hinted by justlevy20 is, although i found this:
when trying to launch `~/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1258-linux-x64/server/rust-analyzer --version` (which is where vscode finds the error) outputs:
`/lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.25' not found`
Did rust analyzer increase a version requirement, or did I just happen to mess up my packages?
Cargo commands work fine.

**Comment by blyxyas** [comment]
I have the same error. Maybe weirder.

```bash
 ~/.vscode-insiders/extensions/rust-lang.rust-analyzer-0.4.1298/server ▓▒░ l
total 39M
drwxrwxr-x 2 alejandra alejandra 4.0K Nov 26 14:03 .
drwxrwxr-x 5 alejandra alejandra 4.0K Nov 26 14:03 ..
-rwxr-xr-x 1 alejandra alejandra  39M Nov 26 14:03 rust-analyzer
 ~/.vscode-insiders/extensions/rust-lang.rust-analyzer-0.4.1298/server ▓▒░ ./rust-analyzer
zsh: no such file or directory: ./rust-analyzer
```
I have Visual Studio Code Insiders installed in Pop Os using snap (Using nightly rust). Yesterday it was working fine.

**Comment by NotThatRqd** [comment]
I also have this problem

**Comment by mczgcy** [comment]
I also have this problem. I installed rust-analyzer-0.3.2037, but VSCode search the server in the rust-analyzer-0.4.2030(previously installed).
