### ISSUE TITLE
Rust Analyzer Appears to Be Invalidating The Cargo Build Cache

### ISSUE THREAD

**Issue by zicklag** [rust-analyzer/rust-analyzer#6136]
I've noticed that when Rust analyzer runs `cargo check` on my projects with native dependencies such as `alsa-sys` or `openssl-sys`, the cargo check for some reason starts back up at that native dependency and invalidates the cargo cache, making me have to rebuild all the crates from `alsa-sys` up to my crate when I run `cargo build`, even though only my crate has actually changed. This makes iterations a lot slower than they have to be because both the `cargo check` by Rust analyzer *and* my actual `cargo build` are building things it doesn't have to.

If I do a `cargo check` from the commandline, that doesn't happen. It just checks my crate because it's the only one that changed.

I'm not sure what the root cause of the issue is. Is anybody else experiencing this issue? I unfortunately have to run the rust analyzer server in a container and have a custom command that starts rust analyzer in the container, so it's a pretty specialized setup and it could be specific to my environment. If nobody can reproduce, then I might just have to see if I can find anything wrong in my environment, I just wanted to make sure there was nothing anybody knew that might cause the issue.

**Comment by bjorn3** [comment]
If you run rust-analyzer in a container it is quite possible that there are env var differences that require a rebuild.

**Comment by bjorn3** [comment]
Does any of the env vars passed to `env_var_os` in https://github.com/rust-lang/pkg-config-rs/blob/master/src/lib.rs differ?

**Comment by zicklag** [comment]
Haha! Thank you! It was `PKG_CONFIG_PATH`. I had in my `.bashrc`:

```
export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/home/zicklag/.local/share"
```

Every time you run `bash`, then it would *append* the pkg-config path to the previous value of pkg-config path, which would make it *different*.

Fixing this will save me *ton* of time in my iterations. It's been bugging me for a while, but I only just figured out that it was only caused when rust-analyzer ran.

Thanks again! :smiley:

**Comment by kassens** [comment]
I'm also running into a similar cache invalidation. Not sure if there's something RA could do, but would be amazing if it could warn against this invalidation somehow. I haven't found the root cause yet, maybe it's some env variable or something todo with workspaces.

**Comment by kassens** [comment]
I found the cache difference by setting by running cargo with `CARGO_LOG=cargo::core::compiler::fingerprint` set.

This showed that in my slightly weird setup I had:

```
Cargo.toml # workspace file
foo/bar/Cargo.toml # some crate
foo/.cargo/config.toml # setting build.rustflags
```

Where only one of cargo or RA used the buildflags until I created a `.cargo/config.toml` in the workspace root.

**Comment by Tyilo** [comment]
I encountered a similar problem.
Deleting my `target` directory fixed it.

**Comment by Hunter522** [comment]
> Haha! Thank you! It was `PKG_CONFIG_PATH`. I had in my `.bashrc`:
> 
> ```
> export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/home/zicklag/.local/share"
> ```
> 
> Every time you run `bash`, then it would _append_ the pkg-config path to the previous value of pkg-config path, which would make it _different_.
> 
> Fixing this will save me _ton_ of time in my iterations. It's been bugging me for a while, but I only just figured out that it was only caused when rust-analyzer ran.
> 
> Thanks again! smiley

This was my issue as well. Except I had it in by `.zshrc`.

**Comment by kevinushey** [comment]
Thanks! I was seeing this as well; in our case, it was because we had this defined in `.cargo/config.toml` in the root of a multi-workspace project:

```
[build]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]
```

and @kassens advice helped us realize that this is why the fingerprint was changing.

One workaround is to specify a custom check directory for rust-analyzer, e.g.

```
{
    "rust-analyzer.checkOnSave.extraArgs": [
        "--target-dir", "${workspaceFolder}/target/check"
    ]
}
```

so that you don't risk fingerprint "collisions" if the specified flags happen to differ between different invocations of `cargo check`.

**Comment by helinwang** [comment]
The problem in my case is I am using emacs service in Nix. And Nix starts emacs with bash, and I am using zsh. There likely are some differences in the rust-analyzer started in bash and cargo build started from zsh. Changing the Nix configuration to let emacs start from zsh fixed the problem for me:

```
  services.emacs = {                                                                                                                                                                
    enable = true;                                                                                                                                                                  
    package = ((pkgs.emacsPackagesFor pkgs.emacs).emacsWithPackages (epkgs: [                                                                                                       
      epkgs.vterm                                                                                                                                                                   
    ]));                                                                                                                                                                            
    defaultEditor = true;                                                                                                                                                           
  };                                                                                                                                                                                
  systemd.user.services.emacs.serviceConfig.ExecStart =                                                                                                                             
    let                                                                                                                                                                             
      cfg = config.services.emacs;                                                                                                                                                  
    in                                                                                                                                                                              
    lib.mkForce "${pkgs.zsh}/bin/zsh -c 'source ${config.system.build.setEnvironment}; exec ${cfg.package}/bin/emacs --daemon'";  
```

**Comment by jymchng** [comment]
I suspect it has to do with this setting in Rust Analyzer
```
"rust-analyzer.cargo.target": null
```

In [Stackoverflow Post](https://stackoverflow.com/questions/71404367/how-to-prevent-rust-cargo-from-compiling-all-dependency-library-when-only-modify), this solution doesn't work for me:
```
export CARGO_TARGET_DIR=~/myproject/target
```

However, when I tried setting rust-analyzer setting on cargo.reload to false, i.e.:
```
"rust-analyzer.cargo.autoreload": false,
```

It works, but I lose the ability to have inlay type hints etc, which sucks.

**Comment by mrchantey** [comment]
My issue was that I had a crate that had a dependency which in turn used `openssl` and it was in regular `dependencies`, so when I switched to `"rust-analyzer.cargo.target": "wasm32-unknown-unknown"` it was tripping up trying to compile for wasm. Fixed by specifying as non-wasm dependency.

```toml
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
fantoccini = { workspace = true }
```

**Comment by raylu** [comment]
I think this has gotten notably worse lately

`CARGO_LOG=cargo::core::compiler::fingerprint cargo b 2>&1 | grep dirty:` says `EnvVarChanged`
in particular, `/home/raylu/.vscode-server/bin/2901c5ac6db8a986a5666c3af51ff804d05af0d4/bin/remote-cli` is on my vscode rust-analyzer path but not my external terminal's path (I am connected to a vscode "remote")

I worked around it by hardcoding my whole `PATH` in the `rust-analyzer.cargo.extraEnv` setting but it feels pretty bad to have to do this

**Comment by Swoorup** [comment]
I am still having this issue. What is the latest fix for this?

**Comment by bjorn3** [comment]
If you want to investigate why, trigger a build by rust-analyzer and then build from a shell with the `-v` argument to make cargo tell you why it rebuilt dependencies.

If you just want to fix it at the cost of more disk space usage, you can set I believe `rust-analyzer.cargo.targetDir` to `true` to make rust-analyzer use a separate target dir from builds you do yourself.
