### ISSUE TITLE
Rust analyser is starting in c# projects(omnisharp)

### ISSUE THREAD

**Issue by jcbritobr** [rust-analyzer/rust-analyzer#6474]
Hello. Rust Analyser thinks csharp projects are rust projects and starts running. Here follow my configuration
rust analyser - v0.2.368
windows 10 64
vscode - 1.50.1

Below are the print of my project
![image](https://user-images.githubusercontent.com/6579862/98264253-7a112000-1f66-11eb-9390-d79003dd624f.png)

Couldn't get a trace from the start but it happens only when I start the vscode under desktop shortcut. If I call $ code . in terminal, it doesn't happens.

**Comment by lnicola** [comment]
Can you reproduce it with an empty ("hello, world") C# project?

**Comment by jcbritobr** [comment]
I'll try to do that.

**Comment by jcbritobr** [comment]
> 
> 
> Can you reproduce it with an empty ("hello, world") C# project? And what is that shortcut pointing to?

Hello! I could reproduce it with a nunit template projetct.
dotnet new nunit -n "test"

![image](https://user-images.githubusercontent.com/6579862/98448713-ecbc0000-210c-11eb-8e43-189ef49586fc.png)

**Comment by bjorn3** [comment]
https://github.com/rust-analyzer/rust-analyzer/blob/f3fe6561c00a07a7d6131db42983cbc3eb658957/editors/code/package.json#L61-L67

It is only supposed to activate for rust files, `Cargo.toml` and a few commands created by rust-analyzer.

**Comment by matklad** [comment]
Activation events look right to me, so I'd guess its a project specific issue (maybe an .rs file somewhere?) rather than ra issue .

**Comment by lnicola** [comment]
This can still happen on very large projects, but we have a different issue filed for that. And I can't reproduce this with an empty project:

![image](https://user-images.githubusercontent.com/308347/116243952-2262ad00-a770-11eb-8d53-cf7fd72a4cb9.png)

**Comment by jcbritobr** [comment]
> 
> 
> Activation events look right to me, so I'd guess its a project specific issue (maybe an .rs file somewhere?) rather than ra issue .

no, it only starts without no reaseon.

**Comment by lnicola** [comment]
Do you have have a very slow disk or a lot of extensions?

**Comment by jcbritobr** [comment]
No, I have only few extensions, but had a time Im not observing this behavior. Maybe it was solved for another bugfix.
![image](https://user-images.githubusercontent.com/6579862/116462968-7d63d500-a840-11eb-9a1d-5601ffea9e03.png)

**Comment by lnicola** [comment]
This was probably the same as https://github.com/rust-analyzer/rust-analyzer/issues/7268 (and #7737).

**Comment by matklad** [comment]
(:eye: for an :eye: : for some reason, omnishap extension starts for me in rust-lang/rust repo)

**Comment by IsakSundeSingh** [comment]
This still happens for me in a C# project. No `.rs`-files, no `.toml` or `Cargo.toml`.
Not really a problem though, just weird 😅
